[package]
name = "macro-toolset"
version = "0.1.0"
authors = ["Hantong Chen"]
edition = "2021"
rust-version = "1.64"

[dependencies]
# Dev
base64 = { version = "0.22", optional = true }
bytes = { version = "1.7", optional = true }

# Encryption
const-hex = { version = "1.13", optional = true }
sha2 = { version = "0.10", optional = true }

[dev-dependencies]
md-5 = "0.10"
rand = "0.8"

[features]
default = ["full"]

# Full features
full = ["macros-base64", "macros-hash", "macros-string-sha256"]

# Base64 related
macros-base64 = ["dep:base64", "dep:bytes"]

# Hash related
macros-hash = ["dep:const-hex"]

# StringExt related
macros-string = ["dep:bytes"]
macros-string-sha256 = ["macros-string", "dep:sha2"]
